# Timeout in seconds that Limine will use before automatically booting
timeout: 5

# The entry name that will be displayed on boot menu
/mangOS
    # We use Limine boot protocol
    protocol: limine
    # Path to the kernel to boot
    path: boot():/boot/mangOS
    # Screen resolution
    resolution: 1280x720x32
